#!/usr/bin/env bash

eval "git show $(\
    git blame $1 -L $2,$3 -w -e --date=raw \
    | sed -r 's/\s+/ /g' | cut -d ' ' --fields=1,4 \
    | sort -n -k2 -r \
    | cut -d ' ' -f 1 \
    | uniq \
    | tr '\n' ' ')"
