#!/bin/bash

curr=$(git rev-parse --abbrev-ref HEAD)
if [[ "$curr" != *"feature/"* ]]; then
  echo "ERROR: source branch must be a feature"
  exit 1
fi
rel="release/$1"
lastv="$(git branch -r --ignore-case | grep release | tail -n 1 | sed -r 's/.*release\/+//g')"
if [[ "${lastv}" != "$1" ]]; then
  echo "ERROR: possibly updating the wrong release (last on remote: ${lastv} != $1)"
  exit 1
fi
git checkout "${rel}"
git pull
git merge $curr
if [ $? = 0 ]; then
  git push
  git checkout $curr
fi
