#!/usr/bin/env -S bash -i

curr=$(git rev-parse --abbrev-ref HEAD)
receiving="$1"
if [ $(git rev-parse --verify "$receiving" 2>/dev/null) ]; then
   # The branch already exists
   git checkout "$receiving" &&
      git cherry-pick \
         --allow-empty \
         --allow-empty-message \
         --keep-redundant-commits \
         "$curr"~"$2".."$curr"
else
   git checkout -b "$receiving"
fi
if [ $? = 0 ]; then
   git checkout "$curr" && git reset --keep HEAD~"$2"
fi
