#!/bin/bash

tmp_dir="/tmp/git-utils"
installed_commands_basename=installed-commands
red_text='\033[0;31m'
green_text='\033[0;32m'
yellow_text='\033[0;33m'
default_text='\033[0m'

print_coloured() {
	echo -e "$1$2"
}

print_warning() {
	print_coloured "${yellow_text}" "WARNING: $1"
}

print_error() {
	print_coloured "${red_text}" "ERROR: $1"
}

print_success() {
	print_coloured "${green_text}" "$1"
}

remove_repo() {
    if [ -d "$1" ]; then
        yes | rm -r $1
    fi
}

create_repo() {
    remove_repo $1
    mkdir -p $1 &&
        cd $1 &&
        git init &&
        git commit -m "initial commit" --allow-empty # Necessary for HEAD
}

split() {
    local str="$1"
    local sep="$2"
    local -n tokens=$3
    local first_in=1
    for i in $(seq ${#sep} 1 ${#str}); do
        local last_in=$((${i}-${#sep}))
        if [[ "$(expr substr "${str}" $((${last_in}+1)) ${#sep})" == "${sep}" ]]; then
            tokens+=("$(expr substr "${str}" ${first_in} $((${last_in}-${first_in}+1)))")
            first_in=$((${i}+1))
        fi
    done
    if [[ ${first_in} != $((${#str}+1)) ]]; then
        tokens+=("$(expr substr "${str}" ${first_in} $((${#str}-${first_in}+1)))")
    fi
}

require_confirmation() {
    echo "$1"
    echo "Do you want to continue?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) return 0 ;;
            No ) return 1 ;;
        esac
    done
}

sort_array() {
  IFS=$'\n' out=($(sort <<< "$*"))
  unset IFS
  echo ${out[@]}
}

drop_duplicates() {
  local input=($(sort_array $@))
  local out=("${input[0]}")
  for i in $(seq 1 1 $((${#input[@]}-1))); do
    if [[ "${input[i]}" == "${input[i-1]}" ]]; then
      continue
    fi
    out+=("${input[i]}")
  done
  echo ${out[@]}
}

index_of() {
  local arr=(${@:1:$#-1})
  shift $(($#-1))
  local el=$1
  for i in $(seq 0 1 $((${#arr[@]}-1))); do
    if [[ "${el}" == "${arr[i]}" ]]; then
      echo $i
      return 0
    fi
  done
  echo -1
}
