#!/bin/bash

root_dir="$(git rev-parse --show-toplevel)"
commands_dir="${root_dir}/commands"
installed_commands_dir="${root_dir}/installed-commands"
curr=$(git rev-parse --abbrev-ref HEAD)
ref=$1
if [[ -z "${ref}" ]]; then
	ref=master
fi

git rev-parse --quiet --verify "${ref}"
if [ $? -ne 0 ]; then
	echo "ERROR: the provided ref does not exist"
	exit 1
fi

rm -r ${installed_commands_dir} 2>/dev/null
mkdir ${installed_commands_dir} 2>/dev/null &&
	git checkout ${ref} &&
	find ${commands_dir}/git-* -type f 2>/dev/null |
	xargs -L 1 -i bash -c 'basename {}' |
		xargs -L 1 -i bash -c "cp --force ${commands_dir}/{} ${installed_commands_dir} 2> /dev/null && \
						   chmod 755 ${installed_commands_dir}/{}"
git checkout ${curr}
