#!/usr/bin/env -S bash -i

root_dir="$(git rev-parse --show-toplevel)"
tests_dir="${root_dir}/tests"

git submodule add https://github.com/bats-core/bats-core.git ${tests_dir}/bats >/dev/null 2>&1
git submodule add https://github.com/bats-core/bats-support.git ${tests_dir}/test_helper/bats-support >/dev/null 2>&1
git submodule add https://github.com/bats-core/bats-assert.git ${tests_dir}/test_helper/bats-assert >/dev/null 2>&1
git submodule update --init >/dev/null 2>&1

which bash > /dev/null
if [[ $? != 0 ]]; then
    echo "ERROR: no 'bash' version installed"
fi

bash_version=$(bash --version 2> /dev/null | head -n 1)
echo "'bash' version the commands will be run and tested with:"
echo "${bash_version}"
${tests_dir}/bats/bin/bats ${tests_dir}
